// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKGGVbJFt14TRjucu1s1iJ4gLgUmgJjJA',
    appId: '1:370491190024:web:0bc933e3b3bb7a65385abd',
    messagingSenderId: '370491190024',
    projectId: 'wr-sfr',
    authDomain: 'wr-sfr.firebaseapp.com',
    storageBucket: 'wr-sfr.firebasestorage.app',
    measurementId: 'G-7XH7J1RT1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcDqV6hWEwO70yMF2JW1MWp-iGqiczp28',
    appId: '1:370491190024:android:999aea400b93870d385abd',
    messagingSenderId: '370491190024',
    projectId: 'wr-sfr',
    storageBucket: 'wr-sfr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCENfcAUr8TuS8QsahazzZQ9W5-xHuXhIs',
    appId: '1:370491190024:ios:edcd2649b211db6d385abd',
    messagingSenderId: '370491190024',
    projectId: 'wr-sfr',
    storageBucket: 'wr-sfr.firebasestorage.app',
    iosBundleId: 'com.example.wrapSafarTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCENfcAUr8TuS8QsahazzZQ9W5-xHuXhIs',
    appId: '1:370491190024:ios:edcd2649b211db6d385abd',
    messagingSenderId: '370491190024',
    projectId: 'wr-sfr',
    storageBucket: 'wr-sfr.firebasestorage.app',
    iosBundleId: 'com.example.wrapSafarTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKGGVbJFt14TRjucu1s1iJ4gLgUmgJjJA',
    appId: '1:370491190024:web:645ced7701bbd61d385abd',
    messagingSenderId: '370491190024',
    projectId: 'wr-sfr',
    authDomain: 'wr-sfr.firebaseapp.com',
    storageBucket: 'wr-sfr.firebasestorage.app',
    measurementId: 'G-REXG4PP020',
  );
}
